### PR TITLE
Added asdf strap

### PR DESCRIPTION
**Pull request by fvumbaca**
Added support for asdf version manager.

```yaml
strapped:
  repo: repo.strapped.sh

brew:
  packages:
    - { name: asdf }

asdf:
  plugins:
    - { name: clojure, url: https://github.com/halcyon/asdf-clojure.git }
    - { name: elixir,  url: https://github.com/asdf-vm/asdf-elixir.git }
  versions:
    - { name: clojure, version: 1.9.0 }
    - { name: elixir,  version: 1.8.2, dir: ~/projects/i-need-a-specific-version }
```

### CODE REVIEW

**Comment by fvumbaca** [comment]
@tk8817 before i merge this in, you mentioned that there should be a version bump. Do we version bump on added straps? I personally feel the straps fall under their own versions and the "main" version is related to the strapped command.

Thoughts?

cc: @MatthewNielsen27

**Comment by azohra** [comment]
To me a new strap means

1. Updated docs website
2. New Strap entry in master strap repo
3. New functionality available for users of master strap repo

Ideally I want a way to let our users know when new functionality is available, and to let the media know what that new functionality is.

I agree the versions are not related, but I think we should do a minor bump of strapped itself as a means of having a release entry marking the new strapped repo feature.

An alternate would be to move the straps to another repo and do releases there.

**Comment by fvumbaca** [comment]
Looking at a [pr to the homebrew-core repo](https://github.com/Homebrew/homebrew-core/pull/41653), they have separated the available packages from the tool, but there is no repo-wide version. The difference I see here is homebrew has a mechanism to discover changes to their repository where we do not besides our documentation. Maybe the problem I am seeing is one of scale - but I do agree there will be issues around discovering new or updated straps.

With our current setup I agree with you that we should bump the minor version. I will update this pr to include that version bump.

I will also raise an issue to discuss this further because moving forward I believe this could cause more work and confusion.

**Comment by azohra** [comment]
@fvumbaca - aligned 100%, lets find a better way forward for future PRs.

**Review by azohra — APPROVED** [review]
Looks great. Lets bump version and lets generate a release.

**Pull request merged**
